[theme]

# Primary accent for interactive elements
primaryColor = '#175e88'

# Background color for the main content area
backgroundColor = '#343a40'

# Background color for sidebar and most interactive widgets #E0E0E0
secondaryBackgroundColor = '#4a5568'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"